name: Release to Production

on:
  push:
    branches-ignore: [ master ]

jobs:
  release:
    name: "Create a release"
    runs-on: ubuntu-latest
    steps:
      - name: "release"
      - run: npx semantic-release
      -
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN}}"
